version: '3.2'

services:
    tarantool_1_7:
        build:
            context: tarantool
            dockerfile: docker/Dockerfile.1.7
        command: tarantool /usr/local/share/tarantool/tarantool.docker.lua
        ports:
            - "3301:3301"
        environment:
            TARANTOOL_USER_NAME: admin
            TARANTOOL_USER_PASSWORD: adminPassword
            TARANTOOL_SLAB_ALLOC_ARENA: 0.1

    tarantool_1_8:
        build:
            context: tarantool
            dockerfile: docker/Dockerfile.1.8
        command: tarantool /usr/local/share/tarantool/tarantool.docker.lua
        ports:
            - "3302:3301"
        environment:
            TARANTOOL_USER_NAME: admin
            TARANTOOL_USER_PASSWORD: adminPassword
            TARANTOOL_SLAB_ALLOC_ARENA: 0.1
            
    tarantool_2_11:
        image: tarantool/tarantool:2.11
        ports:
            - "3311:3301"
        environment:
            TARANTOOL_USER_NAME: admin
            TARANTOOL_USER_PASSWORD: adminPassword

    redis:
        image: redis:3.0-alpine
        command: redis-server
        ports:
            - 6379:6379

    admin:
        image: quay.io/basis-company/tarantool-admin
        ports:
            - 8888:80
        depends_on:
            - tarantool_1_7
            - tarantool_1_8
